"""Initial schema

Revision ID: a2a9e1383021
Revises: 
Create Date: 2026-06-26 19:09:39.953977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2a9e1383021'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partners',
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('bin', sa.String(length=12), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('partner_id')
    )
    op.create_index(op.f('ix_partners_bin'), 'partners', ['bin'], unique=True)
    op.create_table('services',
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('synonyms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('icd_code', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_table('price_documents',
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_format', sa.Enum('pdf', 'docx', 'xlsx', 'scan_pdf', name='fileformatenum'), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('parse_status', sa.Enum('pending', 'processing', 'done', 'error', 'needs_review', name='parsestatusenum'), nullable=True),
    sa.Column('parse_log', sa.Text(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.partner_id'], ),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_table('price_items',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('doc_id', sa.UUID(), nullable=True),
    sa.Column('partner_id', sa.UUID(), nullable=True),
    sa.Column('service_name_raw', sa.String(), nullable=False),
    sa.Column('service_code_source', sa.String(), nullable=True),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('price_resident_kzt', sa.Numeric(), nullable=True),
    sa.Column('price_nonresident_kzt', sa.Numeric(), nullable=True),
    sa.Column('price_original', sa.Numeric(), nullable=True),
    sa.Column('currency_original', sa.Enum('KZT', 'USD', 'RUB', name='currencyenum'), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_note', sa.String(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['price_documents.doc_id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.partner_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.service_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_items')
    op.drop_table('price_documents')
    op.drop_table('services')
    op.drop_index(op.f('ix_partners_bin'), table_name='partners')
    op.drop_table('partners')
    # ### end Alembic commands ###
